name: TNTRun
main: TNTRun\Main
version: 1.0.0
api: 3.11.1
author: BeckenPlayZMCPE
commands:
    tr:
        usage: /tr <sub-command>
        description: All Commands
        permission: TNTRun.command
